### PR TITLE
Added first person option and demo instructions screen

### PR DESCRIPTION
**Pull request by HaileyHurt**

### CODE REVIEW

**Comment by carrieksun** [comment]
can you add a screenshot of what this looks like before we merge it with master?

**Comment by HaileyHurt** [comment]
mmmm, i mean i guess I could but I changed several different scenes in the game so it would be several screenshots, but screenshots wouldn't really capture the functionality, or u can always check the playable version at https://itch.io/search?q=galactic+enterprise . Do u want screenshots though?

**Comment by carrieksun** [comment]
screenshots are just a quick and easy way to approve of a change :P
loading the game is fine too! just takes me a while

On Thu, Sep 29, 2016 at 12:56 PM, Hailey Hurt notifications@github.com
wrote:

> mmmm, i mean i guess I could but I changed several different scenes in the
> game so it would be several screenshots, but screenshots wouldn't really
> capture the functionality, or u can always check the playable version at
> https://itch.io/search?q=galactic+enterprise
> https://urldefense.proofpoint.com/v2/url?u=https-3A__itch.io_search-3Fq-3Dgalactic-2Benterprise&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=pS-cchutsmRAH_r3yKVbrZsiYKqYTl5nl70Z3nHZ4f8&e=
> . Do u want screenshots though?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_2017csun_2D-2DConflict-2DResolution_pull_7-23issuecomment-2D250573618&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=3paBw5NbJ0lzkNlAy6dVhJulkwwiaNIBVyil4ZwHYwo&e=,
> or mute the thread
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFilxLvJjxOWyNLX6PegEoDxMMCNDURIks5qvBfagaJpZM4KKUnM&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=KcNfVzGtwsXmh3dEPu3RU-JXgyf4EeKFf5myssQXk5E&e=
> .

## 

-Carrie

**Comment by carrieksun** [comment]
i don't see the 1st/3rd person checkbox? but i see the instructions screen.

On Thu, Sep 29, 2016 at 1:05 PM, Carrie Sun carrie.k.sun@gmail.com wrote:

> screenshots are just a quick and easy way to approve of a change :P
> loading the game is fine too! just takes me a while
> 
> On Thu, Sep 29, 2016 at 12:56 PM, Hailey Hurt notifications@github.com
> wrote:
> 
> > mmmm, i mean i guess I could but I changed several different scenes in
> > the game so it would be several screenshots, but screenshots wouldn't
> > really capture the functionality, or u can always check the playable
> > version at https://itch.io/search?q=galactic+enterprise
> > https://urldefense.proofpoint.com/v2/url?u=https-3A__itch.io_search-3Fq-3Dgalactic-2Benterprise&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=pS-cchutsmRAH_r3yKVbrZsiYKqYTl5nl70Z3nHZ4f8&e=
> > . Do u want screenshots though?
> > 
> > —
> > You are receiving this because you were assigned.
> > Reply to this email directly, view it on GitHub
> > https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_2017csun_2D-2DConflict-2DResolution_pull_7-23issuecomment-2D250573618&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=3paBw5NbJ0lzkNlAy6dVhJulkwwiaNIBVyil4ZwHYwo&e=,
> > or mute the thread
> > https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFilxLvJjxOWyNLX6PegEoDxMMCNDURIks5qvBfagaJpZM4KKUnM&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=vi3lkALp8X-X8pXaz2ZuKycXvj5NVQK9QIYRnhHbWJ8&s=KcNfVzGtwsXmh3dEPu3RU-JXgyf4EeKFf5myssQXk5E&e=
> > .
> 
> ## 
> 
> -Carrie

## 

-Carrie

**Comment by HaileyHurt** [comment]
its only during the readable scene since thats the only time theres text. Do you mean u don't see the checkbox in unity or in the published game? 
screen shot 2016-09-29 at 1 10 01 pm

**Comment by carrieksun** [comment]
oh i see, i was just confused because i hadn't gotten there yet. it looks
good! the lasers are a nice touch. will merge shortly

On Thu, Sep 29, 2016 at 1:11 PM, Hailey Hurt notifications@github.com
wrote:

> its only during the readable scene since thats the only time theres text.
> Do you mean u don't see the checkbox in unity or in the published game?
> [image: screen shot 2016-09-29 at 1 10 01 pm]
> https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_6414166_18970450_31404ea4-2D8646-2D11e6-2D95d2-2Db465b1f4e25a.png&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=jx1LuerpogoxUpDhFYKXQBMZVXyIFOGQKwXQ04xXs_o&s=fEAyAQqRcxBpojq-JzJj7M8_9cFmeoi_lOOd6tmLnjI&e=
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_2017csun_2D-2DConflict-2DResolution_pull_7-23issuecomment-2D250577379&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=jx1LuerpogoxUpDhFYKXQBMZVXyIFOGQKwXQ04xXs_o&s=3p_W3a5gN8iB8oGi30dYtKdYfACpnMTLngPQWIynkP0&e=,
> or mute the thread
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFilxBg68fZ9nE02WiZjYwOBpmYAhWy4ks5qvBtkgaJpZM4KKUnM&d=DQMFaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=0vczlg-aDsHaXX76YKd8cQ&m=jx1LuerpogoxUpDhFYKXQBMZVXyIFOGQKwXQ04xXs_o&s=Ec73M0bZaGVyY1IDRzMxl5K1KJNsBZVOQdKdI5G1RU0&e=
> .

## 

-Carrie

**Pull request merged**
